# Generated by Django 4.2.5 on 2023-09-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decision_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_set', to='decision_system.restaurant'),
        ),
    ]
