# Generated by Django 4.2.5 on 2023-09-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_system', '0005_remove_restaurant_number_of_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
